### ISSUE TITLE
ick should not change the database name

### ISSUE THREAD

**Issue by CristianCantoro** [elliottslaughter/integrity-checker#5]
> @elliottslaughter wrote:
> > @elliottslaughter wrote:
> > it wasn't obvious to me whether to pass in the full name of the database (e.g. db.json.gz), or just the db name (db)
> 
> Thinking about this some more, I agree with this. I think the tool really shouldn't be doing any magic with the filenames (e.g. you wouldn't expect `tar` to automatically add `.tar.gz` to the name of your archive). This is probably worth another issue so we don't forget.

I am splitting this from issue #2, as pointed out there the fact that `ics` automatically sets the extensions to `.json.gz` is confusing. In particular:

1. `$ ick build datadb data`, produces a db file called `datadb.json.gz`.
2. `$ ick build datadb.foo data`, still produces a db file called `datadb.json.gz`.
3. `$ ick build datadb.foo.bar data`, produces a db file called `datadb.foo.json.gz`.

As suggest above, `ick` should **not** change the name of the db as passed from the CLI.

**Comment by elliottslaughter** [comment]
I agree with this, happy to take the PR when it's passing.

**Comment by elliottslaughter** [comment]
Fixed by #6.
